---
title: "circos_from_dataframe"
output: html_document
---


```{r}
# devtools::install_github("jokergoo/circlize")
library(circlize)
library(tidyverse)
```



```{r}
set.seed(999)
n = 1000
df = data.frame(factors = sample(letters[1:8], n, replace = TRUE),
    x = rnorm(n), y = runif(n))
```


```{r}
df
```




```{r}
# save into pdf file
# pdf("sample.pdf", 7, 5)
plot.new()

circos.par("track.height" = 0.1)

circos.initialize(factors = df$factors, x = df$x)

circos.track(factors = df$factors, y = df$y,
    panel.fun = function(x, y) {
        circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2] + uy(5, "mm"), 
            CELL_META$sector.index)
        circos.axis(labels.cex = 0.6)
})

col = rep(c("#FF0000", "#00FF00"), 4)

circos.trackPoints(df$factors, df$x, df$y, col = col, pch = 16, cex = 0.5)

circos.text(-1, 0.5, "text", sector.index = "a", track.index = 1)

bgcol = rep(c("#EFEFEF", "#CCCCCC"), 4)

circos.trackHist(df$factors, df$x, bin.size = 0.2, bg.col = bgcol, col = NA)

circos.track(factors = df$factors, x = df$x, y = df$y,
    panel.fun = function(x, y) {
        ind = sample(length(x), 10)
        x2 = x[ind]
        y2 = y[ind]
        od = order(x2)
        circos.lines(x2[od], y2[od])
})

circos.update(sector.index = "d", track.index = 2, bg.col = "#FF8080", bg.border = "black")

circos.points(x = -2:2, y = rep(0.5, 5), col = "white")

circos.text(CELL_META$xcenter, CELL_META$ycenter, "updated", col = "white")

circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
    xlim = CELL_META$xlim
    ylim = CELL_META$ylim
    breaks = seq(xlim[1], xlim[2], by = 0.1)
    n_breaks = length(breaks)
    circos.rect(breaks[-n_breaks], rep(ylim[1], n_breaks - 1),
                breaks[-1], rep(ylim[2], n_breaks - 1),
                col = rand_color(n_breaks), border = NA)
})

circos.link("a", 0, "b", 0, h = 0.4)

circos.link("c", c(-0.5, 0.5), "d", c(-0.5,0.5), col = "red", border = "black", h = 0.2)

circos.link("e", 0, "g", c(-1,1), col = "green", border = "black", lwd = 2, lty = 2)

```








```{r}
# save into pdf file
# pdf("sample.pdf", 7, 5)
circos.clear()

plot.new()

circos.par("track.height" = 0.2)

circos.initialize(factors = df$factors, x = df$x)

circos.track(factors = df$factors, y = df$y,
    panel.fun = function(x, y) {
        # circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2] + uy(5, "mm"), 
        #     CELL_META$sector.index)
        circos.axis(labels.cex = 0.5)
})

col = rep(c("#FF0000", "#00FF00"), 4)

circos.trackPoints(df$factors, df$x, df$y, col = col, pch = 16, cex = 0.5)



# bgcol = rep(c("#EFEFEF", "#EFEFEF"), 4)

circos.trackHist(df$factors, df$x, bin.size = 0.5, bg.col ='white', col = 'blue')
# 
# circos.trackHist(df$factors, df$x, bin.size = 0.3, bg.col ='white', col = df$factors)
```







```{r}
ptt_genome <- read_delim('NC_003030_edit.ptt', delim = '\t') 
ptt_plasmid <- read_delim('NC_001988_edit.ptt', delim = '\t') 
```



```{r}
# ptt <- bind_rows(ptt_genome, ptt_plasmid) 

ptt <- bind_rows(ptt_genome=ptt_genome, ptt_plasmid=ptt_plasmid, .id = 'dna')
ptt$dna <- str_replace_all(ptt$dna, "ptt_genome", "Genome")
ptt$dna <- str_replace_all(ptt$dna, "ptt_plasmid", "Plasmid")

# ptt %>% 
#   tail(100)

ptt <- ptt %>% 
  separate(Location, c("start", "end")) %>% 
  rename(name = Synonym)

ptt <- ptt %>% 
  select(start, end, name, dna) %>% 
  mutate(
    start = as.numeric(start), 
    end = as.numeric(end)
  )
```



```{r}
ptt
```



```{r}
(rna <- read_csv('all.csv') %>% 
    group_by(accession, time, sugar) %>%
    summarise(
      mean = mean(RPKM)# ,
#       se = std(RPKM)
      ) %>% 
  rename(name = accession) %>% 
  filter(time == 'A') %>% 
  filter(sugar == 'glu'))
```










```{r}
test_df <- ptt %>% 
  left_join(., rna, by='name')

test_df  
```

```{r}
(test_df1 <- test_df %>% 
   select(dna, start, end, mean) %>% 
   # rownames_to_column() %>% 
   rename(chr = 'dna') %>% 
   mutate(
     chr = as.factor(chr)
   )
 )
```



```{r}
(glu_a <- read_csv('all.csv') %>% 
  group_by(accession, time, sugar) %>%
  summarise(
    mean = mean(RPKM)
    ) %>% 
  rename(name = accession) %>% 
  filter(time == 'A') %>% 
  filter(sugar == 'glu') %>% 
  left_join(., ptt, by='name') %>% 
  ungroup() %>% 
  select(dna, start, end, mean) %>% 
  rename(chr = 'dna') %>% 
  mutate(
    chr = as.factor(chr)
    )
)
```

```{r}
glu_time <- list(glu_a, glu_b, glu_c)
```





```{r}
# save into pdf file
circos.clear()
# pdf("sample.pdf", 5, 5)

plot.new()

circos.par("track.height" = 0.2)

circos.initialize(factors = test_df$dna, x = test_df$start)

circos.track(factors = test_df$dna, y = test_df$start,
    panel.fun = function(x, y) {
        # circos.text(CELL_META$xcenter, CELL_META$cell.ylim[2] + uy(10, "mm"),
        #     CELL_META$sector.index)
        circos.axis(labels.cex = 0.3)
})

# col = rep(c("#FF0000", "#00FF00"), 4)
# 
# 
# circos.genomicRainfall(test_df1, pch = 20, cex = 0.2) 

circos.genomicRainfall(glu_a, pch = 16, cex = 0.3, col = c("#FF000080"))
circos.genomicRainfall(glu_b, pch = 16, cex = 0.3, col = c("#377EB8"))
# circos.genomicRainfall(glu_c, pch = 16, cex = 0.3)

# circos.genomicRainfall(glu_man, pch = 16, cex = 0.2, col = c("#0000FF80", "#FEFEFE"))
#
# ?circos.genomicRainfall
# # bgcol = rep(c("#EFEFEF", "#EFEFEF"), 4)
# 
# circos.trackHist(test_df$start, test_df$mean, bin.size = 100, bg.col ='white', col = 'blue')
# 
# circos.trackHist(df$factors, df$x, bin.size = 0.3, bg.col ='white', col = df$factors)
```


















# Example

http://www.roymfrancis.com/beautiful-circos-plots-in-r/

```{r}
glu_a
```


```{r}
out_rep <- function(x){
  quantiles <- quantile(x, c(0.05, 0.95))
  x[x < quantiles[1]] <- quantiles[1]
  x[x < quantiles[2]] <- quantiles[2]
}

glu_a$mean <- scales::squish(glu_a$mean, quantile(glu_a$mean, c(0.05, 0.95)))

summary(glu_a)
```



```{r}
ref <- data.frame(V1=c("Genome","Plasmid"))

ref$V2 <- c(3940781, 191953)

ref
```


```{r}
circos.clear()
# pdf("sample.pdf", 5, 5)
                  

col_text <- "grey40"
circos.par("track.height"=0.8, gap.degree=5, cell.padding=c(0,0,0,0))
circos.initialize(factors=ref$V1, xlim=matrix(c(rep(0,2), ref$V2), ncol=2))

# genomes
circos.track(ylim=c(0,1),panel.fun=function(x,y) {
chr=CELL_META$sector.index
xlim=CELL_META$xlim
ylim=CELL_META$ylim
circos.text(mean(xlim),mean(ylim),chr,cex=0.5,col=col_text,
facing="bending.inside",niceFacing=TRUE)
},bg.col="grey90",bg.border=F,track.height=0.06)


# genomes x axis
brk <- c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)*10^6
circos.track(track.index = get.current.track.index(), panel.fun = function(x, y) {
  circos.axis(h="top",major.at=brk,labels=round(brk/10^6,1),labels.cex=0.4,
  col=col_text,labels.col=col_text,lwd=0.7,labels.facing="clockwise")
},bg.border=F)

# gc content
circos.track(factors=glu_a$chr, x=glu_a$start, y=glu_a$mean, panel.fun=function(x,y) {
  circos.lines(x,y,col="grey50",lwd=0.6)
  circos.segments(x0=0,x1=max(ref$V2),y0=0.3,y1=0.3,lwd=0.6,lty="11",col="grey90")
  circos.segments(x0=0,x1=max(ref$V2),y0=0.5,y1=0.5,lwd=0.6,lty="11",col="grey90")
  circos.segments(x0=0,x1=max(ref$V2),y0=0.7,y1=0.7,lwd=0.6,lty="11",col="grey90")
},ylim=range(glu_a$mean),track.height=0.08,bg.border=F)
# gc y axis
circos.yaxis(at=c(0.3,0.5,0.7),labels.cex=0.25,lwd=0,tick.length=0,labels.col=col_text,col="#FFFFFF")


# gc content
circos.track(factors=glu_b$chr, x=glu_b$start, y=glu_b$mean, panel.fun=function(x,y) {
  circos.lines(x,y,col="grey50",lwd=0.6)
  circos.segments(x0=0,x1=max(ref$V2),y0=0.3,y1=0.3,lwd=0.6,lty="11",col="grey90")
  circos.segments(x0=0,x1=max(ref$V2),y0=0.5,y1=0.5,lwd=0.6,lty="11",col="grey90")
  circos.segments(x0=0,x1=max(ref$V2),y0=0.7,y1=0.7,lwd=0.6,lty="11",col="grey90")
},ylim=range(glu_b$mean),track.height=0.08,bg.border=F)
# gc y axis
circos.yaxis(at=c(0.3,0.5,0.7),labels.cex=0.25,lwd=0,tick.length=0,labels.col=col_text,col="#FFFFFF")
```








